In [1]:
print("hello")

hello


In [2]:
import torch

In [3]:
torch.__version__

'2.6.0+cpu'

In [4]:
!nvidia-smi

Tue Feb 11 21:19:04 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.97                 Driver Version: 555.97         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8              1W /   50W |     153MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
if torch.cuda.is_available():
    print(f"GPU is available : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


In [6]:
a=torch.empty(2,3)

In [7]:
type(a)

torch.Tensor

In [8]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(3,4)

tensor([[0.5616, 0.5757, 0.4460, 0.1441],
        [0.2726, 0.8984, 0.8467, 0.0012],
        [0.8997, 0.3301, 0.2107, 0.3049]])

In [12]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [13]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [14]:
torch.tensor([[2,3,4], [4,5,6]])

tensor([[2, 3, 4],
        [4, 5, 6]])

In [15]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
torch.arange(0,10, 2)

tensor([0, 2, 4, 6, 8])

In [17]:
torch.linspace(0,10, steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [18]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
torch.full((2,3), fill_value=10)

tensor([[10, 10, 10],
        [10, 10, 10]])

In [20]:
x=torch.tensor([[2,3,4], [4,5,6]])

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

In [25]:
x+2

tensor([[4, 5, 6],
        [6, 7, 8]])

In [26]:
x-2

tensor([[0, 1, 2],
        [2, 3, 4]])

In [27]:
x*3

tensor([[ 6,  9, 12],
        [12, 15, 18]])

In [28]:
x**2

tensor([[ 4,  9, 16],
        [16, 25, 36]])

In [29]:
x/3

tensor([[0.6667, 1.0000, 1.3333],
        [1.3333, 1.6667, 2.0000]])

In [30]:
c = torch.tensor([1,-2,3,-4])

In [31]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [32]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [33]:
torch.sign(c)

tensor([ 1, -1,  1, -1])

In [34]:
torch.cos(c)

tensor([ 0.5403, -0.4161, -0.9900, -0.6536])

In [35]:
d = torch.tensor([1.2, 2.8, 3.4, 4.6])

In [36]:
torch.round(d)

tensor([1., 3., 3., 5.])

In [37]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [38]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [39]:
torch.randint(0,10, (2,3))

tensor([[8, 1, 8],
        [2, 8, 9]])

In [40]:
e=torch.randint(0,10, (2,3), dtype=torch.float)

In [41]:
torch.sum(e)

tensor(14.)

In [42]:
torch.sum(e, dim=0)

tensor([9., 3., 2.])

In [43]:
torch.max(e)

tensor(7.)

In [44]:
torch.min(e)

tensor(0.)

In [45]:
torch.argmax(e)

tensor(3)

In [46]:
torch.argmin(e)

tensor(4)

In [47]:
e

tensor([[2., 3., 1.],
        [7., 0., 1.]])

In [48]:
f=torch.tensor([[1,2,3], [4,5,6]])

In [49]:
f

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
g = torch.tensor([[5,2], [6,7], [8,3]])

In [51]:
g

tensor([[5, 2],
        [6, 7],
        [8, 3]])

In [52]:
torch.matmul(f,g)

tensor([[41, 25],
        [98, 61]])

In [53]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

In [54]:
vec1

tensor([1, 2])

In [55]:
vec2

tensor([3, 4])

In [56]:
torch.dot(vec1, vec2)

tensor(11)

In [57]:
torch.transpose(f, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [58]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 6., 0.],
        [5., 3., 0.],
        [3., 4., 0.]])

In [59]:
torch.inverse(h)

_LinAlgError: linalg.inv: The diagonal element 3 is zero, the inversion could not be completed because the input matrix is singular.

In [60]:
torch.log(h)

tensor([[1.6094, 1.7918,   -inf],
        [1.6094, 1.0986,   -inf],
        [1.0986, 1.3863,   -inf]])

In [61]:
torch.exp(h)

tensor([[148.4132, 403.4288,   1.0000],
        [148.4132,  20.0855,   1.0000],
        [ 20.0855,  54.5981,   1.0000]])

In [62]:
torch.softmax(h, dim=0)

tensor([[0.4683, 0.8438, 0.3333],
        [0.4683, 0.0420, 0.3333],
        [0.0634, 0.1142, 0.3333]])

In [63]:
def dy_dx(x):
    return 2 * x

In [64]:
dy_dx(4)

8

In [65]:
import torch

x=torch.tensor(3.0, requires_grad=True)

In [66]:
x

tensor(3., requires_grad=True)

In [67]:
y=x**2

In [68]:
y

tensor(9., grad_fn=<PowBackward0>)

In [69]:
y=2*x

In [70]:
y

tensor(6., grad_fn=<MulBackward0>)

In [71]:
y.backward()

In [72]:
x.grad

tensor(2.)

In [73]:
import math

def dz_dx(x):
    return 2*x*math.cos(x**2)

In [74]:
dz_dx(3)

-5.466781571308061

In [75]:
dz_dx(5)

9.912028118634735

In [76]:
x=torch.tensor(3.0, requires_grad=True)

In [77]:
y=x**2
z=torch.sin(y)

In [78]:
y

tensor(9., grad_fn=<PowBackward0>)

In [79]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [80]:
x.grad

In [81]:
import torch.nn as nn

In [99]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear = nn.Linear(new_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [100]:
data=torch.rand(10, 5)

In [101]:
data.shape

torch.Size([10, 5])

In [102]:
data.shape[1]

5

In [105]:
model=Model(data.shape[1])

In [104]:
class Test():
    def __init__(self):
        print("Init hello")
    def test(self):
        print("Test hello")
    def __call__(self):
        print("call hello")

In [92]:
obj=Test()

Init hello


In [93]:
obj.test()

Test hello


In [94]:
obj()

call hello


In [106]:
model(data)

tensor([[0.5976],
        [0.6487],
        [0.5231],
        [0.5584],
        [0.6000],
        [0.4630],
        [0.5616],
        [0.6398],
        [0.5780],
        [0.5961]], grad_fn=<SigmoidBackward0>)

In [107]:
model.forward(data)

tensor([[0.5976],
        [0.6487],
        [0.5231],
        [0.5584],
        [0.6000],
        [0.4630],
        [0.5616],
        [0.6398],
        [0.5780],
        [0.5961]], grad_fn=<SigmoidBackward0>)

In [108]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear1 = nn.Linear(new_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [109]:
data = torch.rand(10, 5)

In [110]:
data

tensor([[0.2501, 0.6979, 0.4655, 0.2155, 0.9433],
        [0.5244, 0.8970, 0.4694, 0.0232, 0.8054],
        [0.3013, 0.4196, 0.8463, 0.3019, 0.1271],
        [0.2761, 0.5507, 0.0166, 0.6383, 0.6200],
        [0.0174, 0.7504, 0.6716, 0.4446, 0.9367],
        [0.6300, 0.6463, 0.9457, 0.6916, 0.3774],
        [0.6933, 0.5185, 0.2923, 0.5228, 0.0441],
        [0.4011, 0.8124, 0.9400, 0.7443, 0.0994],
        [0.4703, 0.9789, 0.6291, 0.7509, 0.2634],
        [0.2783, 0.1562, 0.5940, 0.8095, 0.7428]])

In [111]:
model = Model(data.shape[1])

In [112]:
model(data)

tensor([[0.6007],
        [0.6007],
        [0.6007],
        [0.6043],
        [0.6007],
        [0.5999],
        [0.6015],
        [0.6007],
        [0.6016],
        [0.6007]], grad_fn=<SigmoidBackward0>)