In [1]:
print("hello")

hello


In [2]:
import torch

In [3]:
torch.__version__

'2.6.0+cpu'

In [4]:
!nvidia-smi

Tue Feb 11 21:19:04 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.97                 Driver Version: 555.97         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8              1W /   50W |     153MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
if torch.cuda.is_available():
    print(f"GPU is available : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


In [6]:
a=torch.empty(2,3)

In [7]:
type(a)

torch.Tensor

In [8]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(3,4)

tensor([[0.5616, 0.5757, 0.4460, 0.1441],
        [0.2726, 0.8984, 0.8467, 0.0012],
        [0.8997, 0.3301, 0.2107, 0.3049]])

In [12]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [13]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [14]:
torch.tensor([[2,3,4], [4,5,6]])

tensor([[2, 3, 4],
        [4, 5, 6]])

In [15]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
torch.arange(0,10, 2)

tensor([0, 2, 4, 6, 8])

In [17]:
torch.linspace(0,10, steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [18]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
torch.full((2,3), fill_value=10)

tensor([[10, 10, 10],
        [10, 10, 10]])

In [20]:
x=torch.tensor([[2,3,4], [4,5,6]])

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

In [25]:
x+2

tensor([[4, 5, 6],
        [6, 7, 8]])

In [26]:
x-2

tensor([[0, 1, 2],
        [2, 3, 4]])

In [27]:
x*3

tensor([[ 6,  9, 12],
        [12, 15, 18]])

In [28]:
x**2

tensor([[ 4,  9, 16],
        [16, 25, 36]])

In [29]:
x/3

tensor([[0.6667, 1.0000, 1.3333],
        [1.3333, 1.6667, 2.0000]])

In [30]:
c = torch.tensor([1,-2,3,-4])

In [31]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [32]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [33]:
torch.sign(c)

tensor([ 1, -1,  1, -1])

In [34]:
torch.cos(c)

tensor([ 0.5403, -0.4161, -0.9900, -0.6536])

In [35]:
d = torch.tensor([1.2, 2.8, 3.4, 4.6])

In [36]:
torch.round(d)

tensor([1., 3., 3., 5.])

In [37]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [38]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [39]:
torch.randint(0,10, (2,3))

tensor([[8, 1, 8],
        [2, 8, 9]])

In [40]:
e=torch.randint(0,10, (2,3), dtype=torch.float)

In [41]:
torch.sum(e)

tensor(14.)

In [42]:
torch.sum(e, dim=0)

tensor([9., 3., 2.])

In [43]:
torch.max(e)

tensor(7.)

In [44]:
torch.min(e)

tensor(0.)

In [45]:
torch.argmax(e)

tensor(3)

In [46]:
torch.argmin(e)

tensor(4)

In [47]:
e

tensor([[2., 3., 1.],
        [7., 0., 1.]])

In [48]:
f=torch.tensor([[1,2,3], [4,5,6]])

In [49]:
f

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
g = torch.tensor([[5,2], [6,7], [8,3]])

In [51]:
g

tensor([[5, 2],
        [6, 7],
        [8, 3]])

In [52]:
torch.matmul(f,g)

tensor([[41, 25],
        [98, 61]])

In [53]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

In [54]:
vec1

tensor([1, 2])

In [55]:
vec2

tensor([3, 4])

In [56]:
torch.dot(vec1, vec2)

tensor(11)

In [57]:
torch.transpose(f, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [58]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 6., 0.],
        [5., 3., 0.],
        [3., 4., 0.]])

In [59]:
torch.inverse(h)

_LinAlgError: linalg.inv: The diagonal element 3 is zero, the inversion could not be completed because the input matrix is singular.

In [60]:
torch.log(h)

tensor([[1.6094, 1.7918,   -inf],
        [1.6094, 1.0986,   -inf],
        [1.0986, 1.3863,   -inf]])

In [61]:
torch.exp(h)

tensor([[148.4132, 403.4288,   1.0000],
        [148.4132,  20.0855,   1.0000],
        [ 20.0855,  54.5981,   1.0000]])

In [62]:
torch.softmax(h, dim=0)

tensor([[0.4683, 0.8438, 0.3333],
        [0.4683, 0.0420, 0.3333],
        [0.0634, 0.1142, 0.3333]])

In [63]:
def dy_dx(x):
    return 2 * x

In [64]:
dy_dx(4)

8

In [65]:
import torch

x=torch.tensor(3.0, requires_grad=True)

In [66]:
x

tensor(3., requires_grad=True)

In [67]:
y=x**2

In [68]:
y

tensor(9., grad_fn=<PowBackward0>)

In [69]:
y=2*x

In [70]:
y

tensor(6., grad_fn=<MulBackward0>)

In [71]:
y.backward()

In [72]:
x.grad

tensor(2.)

In [73]:
import math

def dz_dx(x):
    return 2*x*math.cos(x**2)

In [74]:
dz_dx(3)

-5.466781571308061

In [75]:
dz_dx(5)

9.912028118634735

In [76]:
x=torch.tensor(3.0, requires_grad=True)

In [77]:
y=x**2
z=torch.sin(y)

In [78]:
y

tensor(9., grad_fn=<PowBackward0>)

In [79]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [80]:
x.grad

In [81]:
import torch.nn as nn

In [99]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear = nn.Linear(new_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [100]:
data=torch.rand(10, 5)

In [101]:
data.shape

torch.Size([10, 5])

In [102]:
data.shape[1]

5

In [105]:
model=Model(data.shape[1])

In [104]:
class Test():
    def __init__(self):
        print("Init hello")
    def test(self):
        print("Test hello")
    def __call__(self):
        print("call hello")

In [92]:
obj=Test()

Init hello


In [93]:
obj.test()

Test hello


In [94]:
obj()

call hello


In [106]:
model(data)

tensor([[0.5976],
        [0.6487],
        [0.5231],
        [0.5584],
        [0.6000],
        [0.4630],
        [0.5616],
        [0.6398],
        [0.5780],
        [0.5961]], grad_fn=<SigmoidBackward0>)

In [107]:
model.forward(data)

tensor([[0.5976],
        [0.6487],
        [0.5231],
        [0.5584],
        [0.6000],
        [0.4630],
        [0.5616],
        [0.6398],
        [0.5780],
        [0.5961]], grad_fn=<SigmoidBackward0>)

In [108]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear1 = nn.Linear(new_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [109]:
data = torch.rand(10, 5)

In [110]:
data

tensor([[0.2501, 0.6979, 0.4655, 0.2155, 0.9433],
        [0.5244, 0.8970, 0.4694, 0.0232, 0.8054],
        [0.3013, 0.4196, 0.8463, 0.3019, 0.1271],
        [0.2761, 0.5507, 0.0166, 0.6383, 0.6200],
        [0.0174, 0.7504, 0.6716, 0.4446, 0.9367],
        [0.6300, 0.6463, 0.9457, 0.6916, 0.3774],
        [0.6933, 0.5185, 0.2923, 0.5228, 0.0441],
        [0.4011, 0.8124, 0.9400, 0.7443, 0.0994],
        [0.4703, 0.9789, 0.6291, 0.7509, 0.2634],
        [0.2783, 0.1562, 0.5940, 0.8095, 0.7428]])

In [111]:
model = Model(data.shape[1])

In [112]:
model(data)

tensor([[0.6007],
        [0.6007],
        [0.6007],
        [0.6043],
        [0.6007],
        [0.5999],
        [0.6015],
        [0.6007],
        [0.6016],
        [0.6007]], grad_fn=<SigmoidBackward0>)

In [113]:
model.linear1.weight

Parameter containing:
tensor([[-0.2300,  0.2731, -0.4030, -0.0043, -0.1679],
        [ 0.3577,  0.0139,  0.0454,  0.1388,  0.1055],
        [ 0.0368,  0.1846, -0.0399, -0.3562, -0.2683]], requires_grad=True)

In [114]:
model.linear1.bias

Parameter containing:
tensor([ 0.1818, -0.3702, -0.2641], requires_grad=True)

In [116]:
class Model(nn.Module):
    def __init__(self, num_features):
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        out = self.network(features)
        return out

In [117]:
data = torch.rand(10, 5)

In [118]:
model=Model(data.shape[1])

AttributeError: cannot assign module before Module.__init__() call

In [119]:
from torchinfo import summary

In [120]:
summary(model, input=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [121]:
import pandas as pd

In [122]:
data=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [123]:
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [124]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [125]:
data.shape

(569, 33)

In [127]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [128]:
df=data.drop(columns=["id", "Unnamed: 32"])

In [129]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [134]:
df["diagnosis"].value_counts

<bound method IndexOpsMixin.value_counts of 0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object>

In [131]:
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [135]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [136]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [137]:
X_train

array([[-0.25951179,  2.03290676, -0.29132105, ..., -0.54544042,
        -0.70414535, -1.09023165],
       [-0.85792595, -1.43297845, -0.88245662, ..., -0.93335265,
        -0.04451377, -0.90589983],
       [-0.72720441, -1.48850665, -0.73604403, ..., -0.46776305,
        -0.19318721,  0.20569384],
       ...,
       [ 2.61055228,  0.1287522 ,  2.54494829, ...,  1.77728688,
         0.03922184, -0.6229589 ],
       [-0.55871887, -1.20161095, -0.61325998, ..., -1.51142413,
        -1.01174557, -1.31770495],
       [-0.07359671,  0.07553768, -0.13098449, ..., -0.87260293,
        -0.63578975, -0.82802104]])

In [139]:
X_test

array([[ 0.76592608,  0.53595901,  0.77280738, ...,  1.06379416,
         3.380102  ,  0.13677951],
       [ 3.2293009 ,  1.30409913,  3.36350862, ...,  2.73124721,
        -0.90579438,  1.18842332],
       [-0.3611841 , -1.37745025, -0.37824034, ...,  0.02282252,
        -0.85965435,  0.09195719],
       ...,
       [ 0.02517068,  1.04959487,  0.04580766, ...,  0.99893118,
         3.14256627,  1.04835356],
       [-1.47028375, -0.08641958, -1.33815   , ...,  0.00700228,
         0.4271399 ,  1.21083449],
       [ 0.79497531,  0.04314623,  0.70107786, ..., -0.46981968,
        -0.61186528, -1.35412309]])

In [140]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,

In [141]:
y_test

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0])

In [142]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))


In [143]:
type(X_train_tensor)

torch.Tensor

In [150]:
class MySimpleNN(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear1 = nn.Linear(new_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [145]:
df.shape

(569, 31)

In [146]:
X_train.shape

(455, 30)

In [155]:
learning_rate = 0.1
epochs = 30

In [156]:
loss_function = nn.BCELoss()

In [157]:
model = MySimpleNN(X_train.shape[1])

In [158]:
optimizer=torch.optim.SGD(model.parameters(), lr = learning_rate)

In [159]:
for epoch in range(epochs):
    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    loss.backward()

    # parameter update
    optimizer.step()

    # print loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.74991375207901
Epoch: 2, Loss: 0.7403908371925354
Epoch: 3, Loss: 0.731981635093689
Epoch: 4, Loss: 0.7243198752403259
Epoch: 5, Loss: 0.7171916961669922
Epoch: 6, Loss: 0.710505485534668
Epoch: 7, Loss: 0.7043251991271973
Epoch: 8, Loss: 0.6983234882354736
Epoch: 9, Loss: 0.6924149990081787
Epoch: 10, Loss: 0.6864058375358582
Epoch: 11, Loss: 0.6802770495414734
Epoch: 12, Loss: 0.6740460991859436
Epoch: 13, Loss: 0.6676695346832275
Epoch: 14, Loss: 0.6611186861991882
Epoch: 15, Loss: 0.6544252634048462
Epoch: 16, Loss: 0.6476138830184937
Epoch: 17, Loss: 0.640710175037384
Epoch: 18, Loss: 0.6336044073104858
Epoch: 19, Loss: 0.6263014674186707
Epoch: 20, Loss: 0.6187728047370911
Epoch: 21, Loss: 0.6109819412231445
Epoch: 22, Loss: 0.6029391288757324
Epoch: 23, Loss: 0.5946630835533142
Epoch: 24, Loss: 0.586259126663208
Epoch: 25, Loss: 0.5777337551116943
Epoch: 26, Loss: 0.5690990686416626
Epoch: 27, Loss: 0.5604162812232971
Epoch: 28, Loss: 0.5517597794532776
Epoch: 

In [160]:
X_test_tensor.shape

torch.Size([114, 30])

In [162]:
model.forward(X_test_tensor[0])

tensor([0.6753], grad_fn=<SigmoidBackward0>)

In [163]:
y_pred = model.forward(X_test_tensor[0])

In [165]:
(y_pred>0.5).float()

tensor([1.])

In [166]:
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy.item()}")

Accuracy : 0.5350877046585083


## Data Loader and DatsSet

In [167]:
from sklearn.datasets import make_classification
import torch

In [168]:
## Step 1 : Create a synthetic classification dataset using sklearn

X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [169]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [170]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [172]:
# Convert data to Pytorch tensors

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

C:\Users\Suraj\AppData\Local\Temp\ipykernel_20756\1386733253.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)


In [173]:
x

tensor(3., requires_grad=True)

In [174]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [175]:
type(x)

torch.Tensor

In [179]:
from torch.utils.data import Dataset, DataLoader

In [193]:
class CustomDataSet(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [194]:
dataset = CustomDataSet(X, y)

In [195]:
len(dataset)

10

In [196]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [197]:
dataloader=DataLoader(dataset, batch_size=2, shuffle=False)

In [198]:
dataloader

In [199]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("*"*90)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
******************************************************************************************
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
******************************************************************************************
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
******************************************************************************************
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
******************************************************************************************
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
******************************************************************************************
