In [1]:
print("hello")

hello


In [2]:
import torch

In [3]:
torch.__version__

'2.6.0+cpu'

In [5]:
!nvidia-smi

Sat Feb  8 12:30:48 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.97                 Driver Version: 555.97         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   60C    P8              1W /   50W |     182MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [8]:
if torch.cuda.is_available():
    print(f"GPU is available : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


In [11]:
a=torch.empty(2,3)

In [12]:
type(a)

torch.Tensor

In [13]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.rand(3,4)

tensor([[0.1796, 0.6402, 0.6401, 0.3876],
        [0.5956, 0.6796, 0.0969, 0.2925],
        [0.7441, 0.9187, 0.7979, 0.9949]])

In [17]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [18]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [20]:
torch.tensor([[2,3,4], [4,5,6]])

tensor([[2, 3, 4],
        [4, 5, 6]])

In [21]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(0,10, 2)

tensor([0, 2, 4, 6, 8])

In [23]:
torch.linspace(0,10, steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [24]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [25]:
torch.full((2,3), fill_value=10)

tensor([[10, 10, 10],
        [10, 10, 10]])

In [26]:
x=torch.tensor([[2,3,4], [4,5,6]])

In [27]:
x.shape

torch.Size([2, 3])

In [28]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

In [32]:
x+2

tensor([[4, 5, 6],
        [6, 7, 8]])

In [33]:
x-2

tensor([[0, 1, 2],
        [2, 3, 4]])

In [34]:
x*3

tensor([[ 6,  9, 12],
        [12, 15, 18]])

In [35]:
x**2

tensor([[ 4,  9, 16],
        [16, 25, 36]])

In [36]:
x/3

tensor([[0.6667, 1.0000, 1.3333],
        [1.3333, 1.6667, 2.0000]])

In [37]:
c = torch.tensor([1,-2,3,-4])

In [38]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [40]:
torch.sign(c)

tensor([ 1, -1,  1, -1])

In [41]:
torch.cos(c)

tensor([ 0.5403, -0.4161, -0.9900, -0.6536])

In [43]:
d = torch.tensor([1.2, 2.8, 3.4, 4.6])

In [44]:
torch.round(d)

tensor([1., 3., 3., 5.])

In [45]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [46]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [49]:
torch.randint(0,10, (2,3))

tensor([[2, 3, 1],
        [7, 0, 1]])

In [52]:
e=torch.randint(0,10, (2,3), dtype=torch.float)

In [ ]:
torch.sum(e)

tensor(23.)

In [54]:
torch.sum(e, dim=0)

tensor([ 9., 13.,  1.])

In [55]:
torch.max(e)

tensor(9.)

In [56]:
torch.min(e)

tensor(0.)

In [58]:
torch.argmax(e)

tensor(4)

In [59]:
torch.argmin(e)

tensor(2)